language: python
python:
  - 3.6
  - nightly
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install fake-factory==0.3

script:
  - py.test --cov
after_success:
  - coveralls
